// Inject a fixture snapshot after planning-dashboard.js has registered its
// message listener. Used only by planning-harness.html (not the VS Code panel).
(function () {
  const today = new Date().toISOString().slice(0, 10);
  const snapshot = {
    objects: [
      { id: "tasks/fresh", type: "task", status: "inbox", title: "Fresh bug", issue_kind: "bug", priority: "p1" },
      { id: "ideas/auto1", type: "idea", status: "capture", title: "Night idea", tags: '["autogenerated"]' },
      { id: "ideas/appr", type: "idea", status: "capture", title: "Approved idea", auto_implement: "ready", implement_backend: "grok", implement_model: "grok-4.6" },
      { id: "tasks/appr2", type: "task", status: "today", title: "Approved task", target_repo: "code-build-vscode" },
      { id: "tasks/wip", type: "task", status: "in_progress", title: "Being built", issue_kind: "feature", linked_sessions: '["sess-live"]', has_screenshot: false },
      { id: "tasks/wip2", type: "task", status: "in_progress", title: "Built earlier, session ended", target_repo: "code-sessions-vscode", linked_sessions: '["sess-old"]', has_screenshot: false },
      { id: "tasks/shipped", type: "task", status: "done", title: "Shipped", target_repo: "knowledge-planning", updated: today, linked_sessions: '["sess-old"]', has_screenshot: true },
      { id: "tasks/noproof", type: "task", status: "done", title: "Done, no screenshot", target_repo: "code-sessions-vscode", updated: today, has_screenshot: false }
    ],
    counts: { task: 6, idea: 2 },
    blocked: [],
    board: { date: today },
    autonomous: { enabled: true }
  };
  window.__host.post({
    type: "snapshot",
    data: snapshot,
    implPrefs: { backend: "grok", model: "grok-4.6", effort: "high" }
  });
  // fleet sessions → session chips on pipeline cards (live / ended / ref-linked)
  window.__host.post({
    type: "sessions",
    data: [
      { uuid: "sess-live", title: "Implementing: Being built", host: "air-15", agent: "claude", status: "live-local", lastActivity: Date.now() - 30_000, mtime: Date.now() - 30_000, planningRefs: [], labels: [] },
      { uuid: "sess-old", title: "Shipped it last night", host: "air", agent: "grok", status: "ended", lastActivity: Date.now() - 7_200_000, mtime: Date.now() - 7_200_000, planningRefs: [], labels: [] },
      { uuid: "sess-ref", title: "Ref-linked via envelope", host: "air-15", agent: "claude", status: "open", lastActivity: Date.now() - 600_000, mtime: Date.now() - 600_000, planningRefs: ["tasks/appr2"], labels: [] }
    ]
  });
  window.__host.post({ type: "setView", view: "pipeline" });
  window.__host.post({ type: "loadStatus", data: { phase: "ready", detail: "harness fixture" } });
})();
