// Coding pipeline view: bugs/features/auto CODING items (tasks/ideas with
// issue_kind, target_repo, an implement route, or the autogenerated tag) in
// one lifecycle — inbox → approved → in progress → implementation → done — separate from the
// per-type Board. Reuses the mini-DOM approach of planningDashboardRender.test.ts.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { runInNewContext } from "node:vm";
import {
  DEFAULT_IMPL_ROUTE,
  pipelineMoveKicks,
  pipelineStatusForLane,
  resolveImplRoute,
  resolveOpenCbTarget,
  mapCbBackend,
  isNativeTranscriptPath,
  planContinueInCodeBuild,
} from "../../src/planningPipeline";

const src = readFileSync(resolve(__dirname, "../../media/planning-dashboard.js"), "utf8");

type El = {
  tagName: string;
  id: string;
  className: string;
  children: El[];
  parent: El | null;
  dataset: Record<string, string>;
  attrs: Record<string, string>;
  style: Record<string, string>;
  textContent: string;
  value: string;
  title: string;
  focus: () => void;
  innerHTML: string;
  selected?: boolean;
  draggable?: boolean;
  listeners: Record<string, Array<(ev: FakeEvent) => void>>;
  classList: { add: (...c: string[]) => void; remove: (...c: string[]) => void; toggle: (c: string, on?: boolean) => void; contains: (c: string) => boolean };
  appendChild: (c: El) => El;
  insertBefore: (c: El, ref: El | null) => El;
  addEventListener: (t: string, fn: (...a: unknown[]) => void) => void;
  querySelector: (sel: string) => El | null;
  querySelectorAll: (sel: string) => El[];
  closest: (sel: string) => El | null;
  setAttribute: (k: string, v: string) => void;
  getAttribute: (k: string) => string | null;
};

type FakeEvent = {
  type: string;
  target: El | { value?: string };
  preventDefault: () => void;
  stopPropagation: () => void;
  shiftKey?: boolean;
  ctrlKey?: boolean;
  metaKey?: boolean;
  dataTransfer?: {
    setData: (k: string, v: string) => void;
    getData: (k: string) => string;
    effectAllowed?: string;
  };
};

function miniDom(snapshot: unknown, state: Record<string, unknown>, initialView?: string, sessions?: unknown[]) {
  const byId = new Map<string, El>();
  const posted: Array<Record<string, unknown>> = [];

  function matches(el: El, sel: string): boolean {
    const s = sel.trim();
    if (s.startsWith("#")) return el.id === s.slice(1);
    if (s.startsWith(".")) return el.className.split(/\s+/).includes(s.slice(1));
    return el.tagName === s.toUpperCase();
  }
  function walk(el: El, acc: El[] = []): El[] {
    acc.push(el);
    for (const c of el.children) walk(c, acc);
    return acc;
  }

  function create(tag: string): El {
    const el: El = {
      tagName: tag.toUpperCase(),
      id: "",
      className: "",
      children: [],
      parent: null,
      dataset: {},
      attrs: {},
      style: {},
      textContent: "",
      value: "",
      title: "",
      innerHTML: "",
      focus: () => {},
      listeners: {},
      classList: {
        add: (...c: string[]) => {
          el.className = [...new Set((el.className || "").split(/\s+/).filter(Boolean).concat(c))].join(" ");
        },
        remove: (...c: string[]) => {
          el.className = (el.className || "").split(/\s+/).filter((x) => x && !c.includes(x)).join(" ");
        },
        toggle: (c: string, on?: boolean) => {
          const has = el.classList.contains(c);
          const should = on === undefined ? !has : on;
          if (should) el.classList.add(c);
          else el.classList.remove(c);
        },
        contains: (c: string) => (el.className || "").split(/\s+/).includes(c),
      },
      appendChild(c: El) {
        c.parent = el;
        el.children.push(c);
        if (c.id) byId.set(c.id, c);
        return c;
      },
      insertBefore(c: El, ref: El | null) {
        c.parent = el;
        const i = ref ? el.children.indexOf(ref) : -1;
        if (i >= 0) el.children.splice(i, 0, c);
        else el.children.push(c);
        if (c.id) byId.set(c.id, c);
        return c;
      },
      addEventListener(t: string, fn: (...a: unknown[]) => void) {
        (el.listeners[t] ||= []).push(fn as (ev: FakeEvent) => void);
      },
      querySelector(sel: string) {
        return el.querySelectorAll(sel)[0] || null;
      },
      querySelectorAll(sel: string) {
        const parts = sel.trim().split(/\s+/);
        return walk(el).slice(1).filter((n) => {
          let node: El | null = n;
          for (let i = parts.length - 1; i >= 0; i--) {
            while (node && !matches(node, parts[i])) {
              if (i === parts.length - 1) return false;
              node = node.parent;
            }
            if (!node) return false;
            if (i > 0) node = node.parent;
          }
          return true;
        });
      },
      closest(sel: string) {
        let n: El | null = el;
        while (n) {
          if (matches(n, sel)) return n;
          n = n.parent;
        }
        return null;
      },
      setAttribute(k: string, v: string) {
        if (k === "id") {
          el.id = v;
          byId.set(v, el);
        }
        if (k === "class") el.className = v;
        el.attrs[k] = v;
        if (k.startsWith("data-")) el.dataset[k.slice(5)] = v;
      },
      getAttribute(k: string) {
        if (k === "id") return el.id || null;
        if (k === "class") return el.className || null;
        return k in el.attrs ? el.attrs[k] : null;
      },
    };
    Object.defineProperty(el, "innerHTML", {
      get() {
        return (el as unknown as { _html?: string })._html || "";
      },
      set(html: string) {
        (el as unknown as { _html?: string })._html = html;
        el.textContent = String(html).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
        el.children = [];
        const re = /<([a-zA-Z0-9]+)([^>]*)>/g;
        let m: RegExpExecArray | null;
        while ((m = re.exec(html))) {
          const child = create(m[1]);
          const id = /id="([^"]+)"/.exec(m[2]);
          const cls = /class="([^"]+)"/.exec(m[2]);
          if (id) {
            child.id = id[1];
            byId.set(id[1], child);
          }
          if (cls) child.className = cls[1];
          const did = /data-id="([^"]+)"/.exec(m[2]);
          if (did) child.dataset.id = did[1];
          const dlane = /data-lane="([^"]+)"/.exec(m[2]);
          if (dlane) child.dataset.lane = dlane[1];
          for (const am of m[2].matchAll(/([a-zA-Z0-9-]+)="([^"]*)"/g)) {
            child.attrs[am[1]] = am[2];
            if (am[1].startsWith("data-")) child.dataset[am[1].slice(5)] = am[2];
          }
          el.appendChild(child);
        }
      },
    });
    return el;
  }

  const body = create("body");
  const ids = [
    "board", "pipeline", "issues", "counts", "overduePill", "inboxPill", "loadOverlay", "loadTitle", "loadDetail",
    "loadTime", "loadRetry", "loadSpin", "viewSeg", "laneSeg", "calModeSeg", "groupBy",
    "sortBy", "addLaneBtn", "inbox", "autonomous", "projects", "sessions", "social",
    "calendar", "graph", "gfilters", "canvas", "backdrop", "drawer", "drawerInner",
    "resmodal", "resTitle", "resSub", "resWarn", "resNote", "resSave", "resSkip", "resCancel",
    "resX", "search", "syncPill", "captureBtn", "refreshBtn", "syncBtn", "topbar", "main",
    "flight",
  ];
  for (const id of ids) {
    const el = create("div");
    el.id = id;
    if (id === "board") el.className = "view";
    body.appendChild(el);
    byId.set(id, el);
  }

  let onMessage: ((e: { data: unknown }) => void) | null = null;
  const windowObj: Record<string, unknown> = {
    __paintTried: false,
    addEventListener: (type: string, fn: (...a: unknown[]) => void) => {
      if (type !== "message") return;
      onMessage = fn as (e: { data: unknown }) => void;
      onMessage({ data: { type: "snapshot", data: snapshot } });
      if (sessions) onMessage({ data: { type: "sessions", data: sessions } });
      if (initialView) onMessage({ data: { type: "setView", view: initialView } });
    },
  };
  const document = {
    body,
    createElement: (tag: string) => create(tag),
    getElementById: (id: string) => byId.get(id) || null,
    querySelector: (sel: string) => {
      const s = sel.trim();
      if (/^#[\w-]+$/.test(s)) return byId.get(s.slice(1)) || null;
      return body.querySelector(s);
    },
    querySelectorAll: (sel: string) => {
      const s = sel.trim();
      if (/^#[\w-]+$/.test(s)) {
        const n = byId.get(s.slice(1));
        return n ? [n] : [];
      }
      return body.querySelectorAll(s);
    },
    addEventListener: () => {},
  };

  const sandbox = {
    acquireVsCodeApi: () => ({
      postMessage: (m: Record<string, unknown>) => posted.push(m),
      getState: () => state,
      setState: () => {},
    }),
    document,
    window: windowObj,
    setInterval: () => 0,
    setTimeout: (fn: () => void) => {
      fn();
      return 0;
    },
    clearTimeout: () => {},
    clearInterval: () => {},
    Date,
    Set,
    Map,
    JSON,
    Number,
    String,
    Math,
    Array,
    Object,
    console,
  };
  (sandbox.window as { document: typeof document }).document = document;
  return { sandbox, byId, posted, fire, host: (m: unknown) => onMessage?.({ data: m }) };
}

function fire(el: El, type: string, init: Partial<FakeEvent> = {}): FakeEvent {
  const store: Record<string, string> = {};
  const ev: FakeEvent = {
    type,
    target: el,
    preventDefault() {},
    stopPropagation() {},
    shiftKey: false,
    ctrlKey: false,
    metaKey: false,
    dataTransfer: {
      setData(k: string, v: string) { store[k] = v; },
      getData(k: string) { return store[k] || ""; },
      effectAllowed: "",
    },
    ...init,
  };
  if (init.dataTransfer) ev.dataTransfer = init.dataTransfer;
  for (const fn of el.listeners[type] || []) fn(ev);
  return ev;
}

const snapshot = {
  objects: [
    { id: "tasks/fresh", type: "task", status: "inbox", title: "Fresh bug", issue_kind: "bug" },
    { id: "ideas/auto1", type: "idea", status: "capture", title: "Night idea", tags: '["autogenerated"]' },
    { id: "ideas/appr", type: "idea", status: "capture", title: "Approved idea", auto_implement: "ready", implement_backend: "grok", implement_model: "grok-4.6" },
    { id: "tasks/appr2", type: "task", status: "today", title: "Approved task", target_repo: "code-build-vscode" },
    { id: "tasks/wip", type: "task", status: "in_progress", title: "Being built", issue_kind: "feature" },
    { id: "ideas/planned", type: "idea", status: "plan", title: "Started idea", target_repo: "code-sessions-vscode" },
    { id: "ideas/running", type: "idea", status: "plan", title: "Running now", linked_sessions: '["sess-linked"]' },
    { id: "tasks/shipped", type: "task", status: "done", title: "Shipped", target_repo: "knowledge-planning", updated: new Date().toISOString().slice(0, 10) },
    // non-coding items — must stay OFF the coding pipeline
    { id: "tasks/errand", type: "task", status: "today", title: "Buy groceries" },
    { id: "thoughts/note", type: "thought", status: "new", title: "A thought" },
    { id: "plans/big", type: "plan", status: "implement", title: "Life plan" },
  ],
  counts: { task: 5, idea: 4, thought: 1, plan: 1 },
  blocked: [],
  board: { date: "2026-09-02" },
  autonomous: {
    enabled: true,
    current_window: {
      start: new Date().toISOString(),
      end: new Date(Date.now() + 3600_000).toISOString(),
      ideate: { status: "done" },
      implement: { status: "running", item: "ideas/running", session: "sess-plan" },
    },
  },
};

function lanesOf(byId: Map<string, El>, container = "pipeline"): Record<string, El> {
  const board = byId.get(container)!;
  const out: Record<string, El> = {};
  for (const col of board.querySelectorAll(".col")) out[col.dataset.lane!] = col;
  return out;
}
function cardIds(col: El): string[] {
  return col.querySelectorAll(".card").map((c) => c.dataset.id!);
}
function allText(n: El): string {
  return [n.textContent || "", ...n.children.map(allText)].join(" ");
}

describe("coding pipeline view", () => {
  it("paints the five lifecycle lanes with coding items only (bugs/auto/approved/started/running/done)", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    expect(() => runInNewContext(src, sandbox, { filename: "planning-dashboard.js" })).not.toThrow();
    const lanes = lanesOf(byId);
    expect(Object.keys(lanes)).toEqual(["inbox", "approved", "in_progress", "implementation", "done"]);
    expect(cardIds(lanes.inbox).sort()).toEqual(["ideas/auto1", "tasks/fresh"]);
    expect(cardIds(lanes.approved).sort()).toEqual(["ideas/appr", "tasks/appr2"]);
    // claimed/started sit in in progress; live auto-implement stays in implementation
    expect(cardIds(lanes.in_progress).sort()).toEqual(["ideas/planned", "tasks/wip"]);
    expect(cardIds(lanes.implementation)).toEqual(["ideas/running"]);
    expect(cardIds(lanes.done)).toEqual(["tasks/shipped"]);
    // column header uses a human label (in progress), dataset.lane stays in_progress
    expect(lanes.in_progress.querySelector("h3")!.innerHTML).toContain("in progress");
    // non-coding items (personal task / thought / plan) never enter the pipeline
    const all = Object.values(lanes).flatMap((l) => cardIds(l));
    expect(all).not.toContain("tasks/errand");
    expect(all).not.toContain("thoughts/note");
    expect(all).not.toContain("plans/big");
  });

  it("renders kind/auto/route chips and a session-opening running chip", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const bug = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/fresh")!;
    expect(bug.innerHTML).toContain("🐛 bug");
    const auto = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "ideas/auto1")!;
    expect(auto.innerHTML).toContain("🤖");
    const routed = lanes.approved.querySelectorAll(".card").find((c) => c.dataset.id === "ideas/appr")!;
    expect(routed.innerHTML).toContain("grok · grok-4.6");
    const running = lanes.implementation.querySelectorAll(".card").find((c) => c.dataset.id === "ideas/running")!;
    expect(running.innerHTML).toContain("▶ implementing");
    expect(running.innerHTML).toContain('data-sess="sess-plan"'); // plan.json session wins over linked_sessions
  });

  it("ignores a stale running marker from a window that ended long ago", () => {
    const stale = JSON.parse(JSON.stringify(snapshot));
    stale.autonomous.current_window.end = new Date(Date.now() - 7200_000).toISOString();
    const { sandbox, byId } = miniDom(stale, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    expect(cardIds(lanes.implementation)).toEqual([]);
    expect(cardIds(lanes.in_progress)).toContain("tasks/wip");
    // no live run → ideas/running has no coding marker at all → off the pipeline
    const all = Object.values(lanes).flatMap((l) => cardIds(l));
    expect(all).not.toContain("ideas/running");
  });

  it("quick-filters by kind (bug / feature / auto)", () => {
    const bugs = miniDom(snapshot, { pipeKind: "bug" }, "pipeline");
    runInNewContext(src, bugs.sandbox, { filename: "planning-dashboard.js" });
    let all = Object.values(lanesOf(bugs.byId)).flatMap((l) => cardIds(l));
    expect(all).toEqual(["tasks/fresh"]);
    const auto = miniDom(snapshot, { pipeKind: "auto" }, "pipeline");
    runInNewContext(src, auto.sandbox, { filename: "planning-dashboard.js" });
    all = Object.values(lanesOf(auto.byId)).flatMap((l) => cardIds(l));
    expect(all).toEqual(["ideas/auto1"]);
    const feats = miniDom(snapshot, { pipeKind: "feature" }, "pipeline");
    runInNewContext(src, feats.sandbox, { filename: "planning-dashboard.js" });
    all = Object.values(lanesOf(feats.byId)).flatMap((l) => cardIds(l));
    expect(all).toEqual(["tasks/wip"]);
  });

  it("filters by project and by worked-on window", () => {
    const withProj = JSON.parse(JSON.stringify(snapshot));
    withProj.objects.forEach((o: any) => {
      if (o.id === "tasks/fresh") { o.project = "projects/code-build"; o.updated = new Date().toISOString().slice(0, 10); }
      if (o.id === "ideas/auto1") { o.project = "projects/kp"; o.updated = "2020-01-01"; }
    });
    const proj = miniDom(withProj, { pipeProject: "projects/code-build" }, "pipeline");
    runInNewContext(src, proj.sandbox, { filename: "planning-dashboard.js" });
    let all = Object.values(lanesOf(proj.byId)).flatMap((l) => cardIds(l));
    expect(all).toEqual(["tasks/fresh"]);
    // week window: tasks/fresh updated today stays; ideas/auto1 from 2020 drops
    const win = miniDom(withProj, { pipeWindow: "week" }, "pipeline");
    runInNewContext(src, win.sandbox, { filename: "planning-dashboard.js" });
    all = Object.values(lanesOf(win.byId)).flatMap((l) => cardIds(l));
    expect(all).toContain("tasks/fresh");
    expect(all).not.toContain("ideas/auto1");
  });

  it("groups cards by project within a lane when ⫶ by project is on", () => {
    const withProj = JSON.parse(JSON.stringify(snapshot));
    withProj.objects.forEach((o: any) => {
      if (o.id === "tasks/fresh") o.project = "projects/code-build";
      if (o.id === "ideas/auto1") o.project = "projects/kp";
    });
    const { sandbox, byId } = miniDom(withProj, { pipeGroupProj: true }, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const inbox = lanesOf(byId).inbox;
    const heads = inbox.querySelectorAll(".planehead").map((h) => h.innerHTML);
    expect(heads).toEqual(["⫶ code-build", "⫶ kp"]);
  });

  it("keeps the Board on classic per-type status lanes (default task lane-set)", () => {
    const { sandbox, byId } = miniDom(snapshot, {});
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId, "board");
    expect(Object.keys(lanes)).toEqual(["inbox", "today", "in_progress", "done", "deferred", "outdated"]);
    // the Board still shows ALL tasks, including non-coding ones
    expect(cardIds(lanes.today)).toContain("tasks/errand");
  });

  it("paints a default route picker (provider · model · effort) on the pipeline filter bar", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    expect(byId.get("ppProv")).toBeTruthy();
    expect(byId.get("ppModel")).toBeTruthy();
    expect(byId.get("ppEffort")).toBeTruthy();
    // options filled from IMPL_PROV / IMPL_EFF
    const provVals = (byId.get("ppProv")!.children || []).map((c) => c.value);
    expect(provVals).toContain("claude");
    expect(provVals).toContain("grok");
  });

  it("changing the pipeline route posts setImplPrefs for grok and for claude", () => {
    const { sandbox, byId, posted } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const prov = byId.get("ppProv")!;
    const model = byId.get("ppModel")!;
    const effort = byId.get("ppEffort")!;
    prov.value = "grok";
    fire(prov, "change");
    expect(model.children.map((c) => c.value)).toEqual(["", "default", "grok-4.6", "grok-4.5", "grok-code-fast-1"]);
    model.value = "grok-4.6";
    fire(model, "change");
    effort.value = "high";
    fire(effort, "change");
    let msg = [...posted].reverse().find((m) => m.action === "setImplPrefs");
    expect(msg).toMatchObject({ backend: "grok", model: "grok-4.6", effort: "high" });
    prov.value = "claude";
    fire(prov, "change");
    expect(model.children.map((c) => c.value)).toEqual(["", "default", "fable", "opus", "sonnet", "haiku"]);
    model.value = "fable";
    fire(model, "change");
    effort.value = "medium";
    fire(effort, "change");
    msg = [...posted].reverse().find((m) => m.action === "setImplPrefs");
    expect(msg).toMatchObject({ backend: "claude", model: "fable", effort: "medium" });
  });

  it("each pipeline lane header has a select-all control", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    for (const col of Object.values(lanes)) {
      const btn = col.querySelector(".laneselect");
      expect(btn).toBeTruthy();
    }
  });

  it("ctrl-click toggles card selection without opening the drawer", () => {
    const { sandbox, byId, posted } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const a = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/fresh")!;
    const b = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "ideas/auto1")!;
    fire(a, "click", { ctrlKey: true, target: a });
    fire(b, "click", { ctrlKey: true, target: b });
    expect(a.classList.contains("selected")).toBe(true);
    expect(b.classList.contains("selected")).toBe(true);
    expect(posted.some((m) => m.type === "show")).toBe(false);
  });

  it("shift-click selects a range within a lane", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const inbox = lanesOf(byId).inbox;
    const cards = inbox.querySelectorAll(".card");
    expect(cards.length).toBeGreaterThanOrEqual(2);
    fire(cards[0], "click", { ctrlKey: true, target: cards[0] });
    fire(cards[cards.length - 1], "click", { shiftKey: true, target: cards[cards.length - 1] });
    expect(cards.every((c) => c.classList.contains("selected"))).toBe(true);
  });

  it("lane select-all after search only selects visible cards", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const search = byId.get("search")!;
    search.value = "Fresh";
    fire(search, "input", { target: search });
    const inbox = lanesOf(byId).inbox;
    const cards = inbox.querySelectorAll(".card");
    const fresh = cards.find((c) => c.dataset.id === "tasks/fresh")!;
    const auto = cards.find((c) => c.dataset.id === "ideas/auto1")!;
    expect(fresh.style.display).not.toBe("none");
    expect(auto.style.display).toBe("none");
    const selAll = inbox.querySelector(".laneselect")!;
    fire(selAll, "click", { target: selAll });
    expect(fresh.classList.contains("selected")).toBe(true);
    expect(auto.classList.contains("selected")).toBe(false);
  });

  function setRoute(byId: Map<string, El>, backend: string, mdl: string, effort: string) {
    const prov = byId.get("ppProv")!;
    const model = byId.get("ppModel")!;
    const pe = byId.get("ppEffort")!;
    prov.value = backend;
    fire(prov, "change");
    model.value = mdl;
    fire(model, "change");
    pe.value = effort;
    fire(pe, "change");
  }

  it("dragging a multi-selection onto implementation posts grok route", () => {
    const { sandbox, byId, posted } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    setRoute(byId, "grok", "grok-4.6", "high");
    const lanes = lanesOf(byId);
    const a = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/fresh")!;
    const b = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "ideas/auto1")!;
    fire(a, "click", { ctrlKey: true, target: a });
    fire(b, "click", { ctrlKey: true, target: b });
    const start = fire(a, "dragstart", { target: a });
    const payload = start.dataTransfer!.getData("text/plain");
    expect(payload.split("\n").sort()).toEqual(["ideas/auto1", "tasks/fresh"]);
    fire(lanes.implementation, "drop", {
      target: lanes.implementation,
      dataTransfer: { setData() {}, getData() { return payload; } },
    });
    const move = posted.find((m) => m.action === "pipelineMove");
    expect(move).toMatchObject({
      lane: "implementation",
      route: { backend: "grok", model: "grok-4.6", effort: "high" },
    });
    expect((move!.ids as string[]).sort()).toEqual(["ideas/auto1", "tasks/fresh"]);
  });

  it("dragging onto implementation with Claude route posts claude · fable · medium", () => {
    const { sandbox, byId, posted } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    setRoute(byId, "claude", "fable", "medium");
    const lanes = lanesOf(byId);
    const a = lanes.inbox.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/fresh")!;
    fire(a, "dragstart", { target: a });
    fire(lanes.implementation, "drop", {
      target: lanes.implementation,
      dataTransfer: { setData() {}, getData() { return "tasks/fresh"; } },
    });
    const move = posted.find((m) => m.action === "pipelineMove");
    expect(move).toMatchObject({
      lane: "implementation",
      ids: ["tasks/fresh"],
      route: { backend: "claude", model: "fable", effort: "medium" },
    });
  });

  it("empty remembered route defaults the picker to grok · grok-4.6 · high", () => {
    const { sandbox, byId } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    expect(byId.get("ppProv")!.value).toBe("grok");
    expect(byId.get("ppModel")!.value).toBe("grok-4.6");
    expect(byId.get("ppEffort")!.value).toBe("high");
  });

  it("dropping onto in_progress posts pipelineMove and does not use the implementation lane", () => {
    const { sandbox, byId, posted } = miniDom(snapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    fire(lanes.in_progress, "drop", {
      target: lanes.in_progress,
      dataTransfer: { setData() {}, getData() { return "tasks/fresh"; } },
    });
    const move = posted.find((m) => m.action === "pipelineMove");
    expect(move).toMatchObject({
      lane: "in_progress",
      ids: ["tasks/fresh"],
      route: { backend: "grok", model: "grok-4.6", effort: "high" },
    });
    expect(posted.filter((m) => m.action === "pipelineMove")).toHaveLength(1);
  });

  it("a live activeImplements() hit stays in implementation even when status is in_progress or plan", () => {
    const live = JSON.parse(JSON.stringify(snapshot));
    live.objects.find((o: { id: string }) => o.id === "tasks/wip").status = "in_progress";
    live.autonomous.current_window.implement.item = "tasks/wip";
    const { sandbox, byId } = miniDom(live, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    expect(cardIds(lanes.implementation)).toEqual(["tasks/wip"]);
    expect(cardIds(lanes.in_progress)).not.toContain("tasks/wip");
  });
});

// ── session chips + done-without-screenshot evidence (1.60.0) ────────────────
const today = new Date().toISOString().slice(0, 10);
const sessSnapshot = {
  objects: [
    { id: "tasks/wip", type: "task", status: "in_progress", title: "Being built", issue_kind: "feature", linked_sessions: '["sess-live"]', has_screenshot: false },
    { id: "tasks/wip2", type: "task", status: "in_progress", title: "Proof ready", target_repo: "csv", has_screenshot: true },
    { id: "tasks/lone", type: "task", status: "in_progress", title: "No session yet", target_repo: "csv" },
    { id: "tasks/refonly", type: "task", status: "today", title: "Ref linked", target_repo: "csv" },
    { id: "tasks/noproof", type: "task", status: "done", title: "Done no proof", target_repo: "csv", updated: today, has_screenshot: false },
    { id: "tasks/proof", type: "task", status: "done", title: "Done with proof", target_repo: "csv", updated: today, has_screenshot: true },
    { id: "tasks/legacy", type: "task", status: "done", title: "Legacy done (unknown)", target_repo: "csv", updated: today },
  ],
  counts: { task: 7 },
  blocked: [],
  board: { date: today },
  autonomous: { enabled: true },
};
const fleet = [
  { uuid: "sess-live", title: "Implementing now", host: "air-15", agent: "claude", source: "claude", projectPath: "/Users/me/docs", status: "live-local", lastActivity: Date.now() - 30_000, mtime: Date.now() - 30_000, planningRefs: [], labels: [] },
  { uuid: "sess-ref", title: "Envelope linked", host: "air", agent: "grok", source: "grok", projectPath: "/Users/me/csv", status: "ended", lastActivity: Date.now() - 7_200_000, mtime: Date.now() - 7_200_000, planningRefs: ["tasks/refonly"], labels: [] },
];

describe("pipeline session chips", () => {
  it("shows a live chip from linked_sessions and opens the centered item panel on click", () => {
    const { sandbox, byId, posted } = miniDom(sessSnapshot, {}, "pipeline", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const wip = lanes.in_progress.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/wip")!;
    expect(wip.innerHTML).toContain("sesschip live");
    expect(wip.innerHTML).toContain("▸ live");
    const chip = wip.querySelectorAll(".sesschip")[0]!;
    fire(wip, "click", { target: chip });
    // chip click → same centered drawer as a card click, never the conversation viewer
    const shown = posted.find((m) => m.type === "show");
    expect(shown).toMatchObject({ id: "tasks/wip" });
    expect(posted.some((m) => m.action === "openSession")).toBe(false);
    expect(byId.get("drawer")!.classList.contains("center")).toBe(true);
    expect(byId.get("drawer")!.classList.contains("hidden")).toBe(false);
  });

  it("⚡ in-flight view buckets live / machine / recent from sessions only and opens the same centered panel as the board", () => {
    const snap = JSON.parse(JSON.stringify(sessSnapshot));
    snap.autonomous = {
      enabled: true,
      current_window: {
        implement: { status: "running", item: "tasks/wip2" },
        end: new Date(Date.now() + 3600_000).toISOString(),
      },
    };
    const { sandbox, byId, posted, host } = miniDom(snap, {}, "flight", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId, "flight");
    expect(Object.keys(lanes)).toEqual(["live", "machine", "recent"]);
    expect(lanes.claimed).toBeUndefined();
    expect(cardIds(lanes.live)).toEqual(["tasks/wip"]); // linked live session
    expect(cardIds(lanes.machine)).toEqual(["tasks/wip2"]); // night implement running
    expect(cardIds(lanes.recent)).toEqual(["tasks/refonly"]); // ended session via planning_refs
    // in_progress with no session must not leak in from KP status
    const all = [...cardIds(lanes.live), ...cardIds(lanes.machine), ...cardIds(lanes.recent)];
    expect(all).not.toContain("tasks/lone");
    expect(all).not.toContain("tasks/noproof");
    const card = lanes.live.querySelectorAll(".card")[0]!;
    fire(card, "click", { target: card });
    expect(posted.find((m) => m.type === "show")).toMatchObject({ id: "tasks/wip" });
    expect(posted.some((m) => m.action === "openSession")).toBe(false);
    const drawer = byId.get("drawer")!;
    expect(drawer.classList.contains("center")).toBe(true);
    expect(drawer.classList.contains("hidden")).toBe(false);
    host({
      type: "detail",
      data: {
        id: "tasks/wip",
        title: "Being built",
        type: "task",
        status: "in_progress",
        body: "notes in the shared panel",
        frontmatter: { issue_kind: "feature", priority: "p1" },
        linked_sessions: ["sess-live"],
      },
    });
    const inner = byId.get("drawerInner")!;
    const text = allText(inner);
    expect(inner.querySelector(".titleEdit")?.value).toBe("Being built");
    expect(text).toContain("Agent actions");
    expect(text).toContain("Notes / details");
    expect(byId.get("sessPane")).toBeTruthy();
    expect(byId.get("sessPane")!.className).toContain("sesspane");
    expect(allText(byId.get("sessPane")!)).toContain("Session activity");
    expect(posted.some((m) => m.type === "requestTranscript" && m.uuid === "sess-live")).toBe(true);
    expect(text).toContain("tasks/wip");
    const openBtn = byId.get("dpathOpen")!;
    expect(openBtn).toBeTruthy();
    expect(openBtn.textContent).toContain("tasks/wip");
    posted.length = 0;
    fire(openBtn, "click", { target: openBtn });
    expect(posted.find((m) => m.action === "openFile")).toMatchObject({
      type: "action",
      action: "openFile",
      id: "tasks/wip",
      relpath: "tasks/wip.md",
    });
    const copyBtn = byId.get("dpathCopy")!;
    fire(copyBtn, "click", { target: copyBtn });
    expect(posted.find((m) => m.action === "copyPath")).toMatchObject({
      type: "action",
      action: "copyPath",
      id: "tasks/wip",
      relpath: "tasks/wip.md",
    });
    posted.length = 0;
    const cbBtn = byId.get("sessPane")!.querySelectorAll("button").find((b) => b.textContent.includes("Code Build"));
    expect(cbBtn).toBeTruthy();
    fire(cbBtn!, "click", { target: cbBtn! });
    expect(posted.find((m) => m.action === "resumeSession")).toMatchObject({
      type: "action",
      action: "resumeSession",
      uuid: "sess-live",
      source: "claude",
      cwd: "/Users/me/docs",
    });
  });

  it("⚡ in-flight empty state is honest when nothing has a live/machine/recent session", () => {
    const snap = JSON.parse(JSON.stringify(sessSnapshot));
    snap.autonomous = { enabled: true };
    const { sandbox, byId } = miniDom(snap, {}, "flight", []);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const root = byId.get("flight")!;
    expect(allText(root)).toContain("Nothing in flight");
    expect(lanesOf(byId, "flight").claimed).toBeUndefined();
    expect(lanesOf(byId, "flight").live).toBeUndefined();
    expect(root.querySelectorAll(".card")).toHaveLength(0);
  });

  it("also picks up sessions linked only via the envelope's planning_refs", () => {
    const { sandbox, byId } = miniDom(sessSnapshot, {}, "pipeline", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const ref = lanes.approved.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/refonly")!;
    expect(ref.innerHTML).toContain('data-sess="sess-ref"');
    expect(ref.innerHTML).toContain("2h ago");
  });

  it("offers a new-session-with-context chip on session-less in-progress cards", () => {
    const { sandbox, byId, posted } = miniDom(sessSnapshot, {}, "pipeline", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const lone = lanes.in_progress.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/lone")!;
    expect(lone.innerHTML).toContain("no session");
    const chip = lone.querySelectorAll(".sesschip")[0]!;
    fire(lone, "click", { target: chip });
    const msg = posted.find((m) => m.action === "openCB");
    expect(msg).toMatchObject({ id: "tasks/lone" });
  });

  it("requests fleet sessions when the pipeline paints without them", () => {
    const { sandbox, posted } = miniDom(sessSnapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    expect(posted.some((m) => m.type === "requestSessions")).toBe(true);
  });
});

describe("done-lane screenshot evidence", () => {
  it("flags done cards with has_screenshot=false and attaches on click", () => {
    const { sandbox, byId, posted } = miniDom(sessSnapshot, {}, "pipeline", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const bad = lanes.done.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/noproof")!;
    expect(bad.innerHTML).toContain("📷 missing");
    const good = lanes.done.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/proof")!;
    expect(good.innerHTML).not.toContain("noshot");
    // unknown (no has_screenshot field, e.g. harness/legacy snapshot) — no badge
    const legacy = lanes.done.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/legacy")!;
    expect(legacy.innerHTML).not.toContain("noshot");
    const badge = bad.querySelectorAll(".noshot")[0]!;
    fire(bad, "click", { target: badge });
    const msg = posted.find((m) => m.action === "attachImage");
    expect(msg).toMatchObject({ id: "tasks/noproof" });
  });

  it("warns in the done-move modal when the item has no screenshot", () => {
    const { sandbox, byId, posted } = miniDom(sessSnapshot, {}, "pipeline", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    fire(lanes.done, "drop", {
      target: lanes.done,
      dataTransfer: { setData() {}, getData() { return "tasks/wip"; } },
    });
    const warn = byId.get("resWarn")!;
    expect(warn.classList.contains("hidden")).toBe(false);
    // mini-DOM textContent doesn't aggregate children — read the message span
    expect(warn.querySelectorAll("span")[0]!.textContent).toContain("no implementation screenshot");
    const attach = warn.querySelectorAll("button")[0]!;
    fire(attach, "click", { target: attach });
    expect(posted.find((m) => m.action === "attachImage")).toMatchObject({ id: "tasks/wip" });
    fire(byId.get("resSkip")!, "click", { target: byId.get("resSkip")! });
    expect(posted.find((m) => m.action === "pipelineMove")).toMatchObject({ lane: "done", ids: ["tasks/wip"] });
  });

  it("keeps the warning hidden when the item has a screenshot", () => {
    const { sandbox, byId } = miniDom(sessSnapshot, {}, "pipeline", fleet);
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    fire(lanes.done, "drop", {
      target: lanes.done,
      dataTransfer: { setData() {}, getData() { return "tasks/wip2"; } },
    });
    expect(byId.get("resWarn")!.classList.contains("hidden")).toBe(true);
  });
});

// ── Implementation lane: every active implement, not just the night item ──────
// activeImplements() sources night (plan.json), grok (grok-plan.json) and
// tonight's slate picks; done keeps precedence and stale running records
// (window end + 1h, or a grok record with no timestamp) are ignored.
const implDate = new Date().toISOString().slice(0, 10);
const multiSnapshot = {
  objects: [
    { id: "tasks/nightbuild", type: "task", status: "inbox", title: "Night building", issue_kind: "feature" },
    { id: "tasks/grokbuild", type: "task", status: "inbox", title: "Grok building", issue_kind: "feature" },
    { id: "tasks/slatepick", type: "task", status: "inbox", title: "Queued tonight", auto_implement: "ready", target_repo: "code-sessions-vscode" },
    { id: "tasks/slateover", type: "task", status: "inbox", title: "Past take budget", auto_implement: "ready", target_repo: "code-sessions-vscode" },
    { id: "tasks/donealready", type: "task", status: "done", title: "Already done", target_repo: "code-sessions-vscode", updated: implDate, has_screenshot: true },
  ],
  counts: { task: 5 },
  blocked: [],
  board: { date: implDate },
  autonomous: {
    enabled: true,
    current_window: {
      start: new Date().toISOString(),
      end: new Date(Date.now() + 3600_000).toISOString(),
      implement: { status: "running", item: "tasks/nightbuild", session: "sess-night" },
    },
    grok_plan: {
      lane: "grok",
      current: { implement: { status: "running", item: "tasks/grokbuild", session: "sess-grok", started: new Date().toISOString() } },
    },
    slate: { date: implDate, take_budget: 1, items: [{ id: "tasks/slatepick" }, { id: "tasks/slateover" }] },
  },
};

describe("implementation lane: all active implements", () => {
  it("shows the night-running item with a running chip + night lane badge", () => {
    const { sandbox, byId } = miniDom(multiSnapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const night = lanes.implementation.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/nightbuild")!;
    expect(night.innerHTML).toContain("▶ implementing");
    expect(night.innerHTML).toContain(">night</span>");
    expect(night.innerHTML).toContain('data-sess="sess-night"');
  });

  it("also shows the grok-lane running item with a grok lane badge", () => {
    const { sandbox, byId } = miniDom(multiSnapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const grok = lanes.implementation.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/grokbuild")!;
    expect(grok.innerHTML).toContain("▶ implementing");
    expect(grok.innerHTML).toContain(">grok</span>");
    expect(grok.innerHTML).toContain('data-sess="sess-grok"');
  });

  it("renders today's slate picks as queued-tonight intent, capped at take_budget", () => {
    const { sandbox, byId } = miniDom(multiSnapshot, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    const pick = lanes.implementation.querySelectorAll(".card").find((c) => c.dataset.id === "tasks/slatepick")!;
    expect(pick.innerHTML).toContain("queued tonight");
    expect(pick.innerHTML).toContain("queuechip");
    expect(pick.innerHTML).not.toContain("▶ implementing"); // intent, not activity
    // beyond take_budget → not queued; auto_implement:ready keeps it in approved
    expect(cardIds(lanes.approved)).toContain("tasks/slateover");
    expect(cardIds(lanes.implementation)).not.toContain("tasks/slateover");
  });

  it("ignores stale running records (window over, or grok record without a timestamp)", () => {
    const stale = JSON.parse(JSON.stringify(multiSnapshot));
    stale.autonomous.current_window.end = new Date(Date.now() - 7200_000).toISOString();
    stale.autonomous.grok_plan.current.implement.started = new Date(Date.now() - 7200_000).toISOString();
    stale.autonomous.slate = null;
    const { sandbox, byId } = miniDom(stale, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    let lanes = lanesOf(byId);
    expect(cardIds(lanes.implementation)).toEqual([]);
    // a grok "running" record with no timestamp at all is untrusted → ignored
    const noHeartbeat = JSON.parse(JSON.stringify(multiSnapshot));
    delete noHeartbeat.autonomous.current_window;
    noHeartbeat.autonomous.slate = null;
    delete noHeartbeat.autonomous.grok_plan.current.implement.started;
    const dom2 = miniDom(noHeartbeat, {}, "pipeline");
    runInNewContext(src, dom2.sandbox, { filename: "planning-dashboard.js" });
    lanes = lanesOf(dom2.byId);
    expect(cardIds(lanes.implementation)).toEqual([]);
  });

  it("keeps done precedence: a running/queued record never pulls a done item back", () => {
    const doneWins = JSON.parse(JSON.stringify(multiSnapshot));
    doneWins.autonomous.current_window.implement.item = "tasks/donealready";
    doneWins.autonomous.slate.items = [{ id: "tasks/donealready" }];
    const { sandbox, byId } = miniDom(doneWins, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    expect(cardIds(lanes.done)).toContain("tasks/donealready");
    expect(cardIds(lanes.implementation)).not.toContain("tasks/donealready");
  });

  it("degrades silently when grok-plan is unparseable junk", () => {
    const junk = JSON.parse(JSON.stringify(multiSnapshot));
    junk.autonomous.grok_plan = { current: "not-an-object", history: 42 };
    junk.autonomous.slate = "garbage";
    const { sandbox, byId } = miniDom(junk, {}, "pipeline");
    runInNewContext(src, sandbox, { filename: "planning-dashboard.js" });
    const lanes = lanesOf(byId);
    expect(cardIds(lanes.implementation)).toEqual(["tasks/nightbuild"]); // night unaffected
  });
});

describe("host pipeline move: kick vs claim + default route", () => {
  it("in_progress never kicks; implementation kicks unless opts.kick is false", () => {
    expect(pipelineMoveKicks("in_progress")).toBe(false);
    expect(pipelineMoveKicks("in_progress", { kick: true })).toBe(false);
    expect(pipelineMoveKicks("implementation")).toBe(true);
    expect(pipelineMoveKicks("implementation", { kick: false })).toBe(false);
    expect(pipelineMoveKicks("approved")).toBe(false);
    expect(pipelineMoveKicks("done")).toBe(false);
  });

  it("maps in_progress / implementation to task@in_progress and idea@plan (no new idea status)", () => {
    expect(pipelineStatusForLane("task", "in_progress")).toBe("in_progress");
    expect(pipelineStatusForLane("idea", "in_progress")).toBe("plan");
    expect(pipelineStatusForLane("task", "implementation")).toBe("in_progress");
    expect(pipelineStatusForLane("idea", "implementation")).toBe("plan");
    expect(pipelineStatusForLane("task", "inbox")).toBe("inbox");
    expect(pipelineStatusForLane("idea", "inbox")).toBe("capture");
    expect(pipelineStatusForLane("task", "approved")).toBeNull();
  });

  it("empty remembered route defaults to Grok · grok-4.6 · high; explicit and remembered win", () => {
    expect(DEFAULT_IMPL_ROUTE).toEqual({ backend: "grok", model: "grok-4.6", effort: "high" });
    expect(resolveImplRoute(undefined, undefined)).toEqual(DEFAULT_IMPL_ROUTE);
    expect(resolveImplRoute({}, { backend: "", model: "", effort: "" })).toEqual(DEFAULT_IMPL_ROUTE);
    expect(resolveImplRoute(undefined, { backend: "-", model: "-", effort: "-" })).toEqual(DEFAULT_IMPL_ROUTE);
    expect(resolveImplRoute({ backend: "claude", model: "fable", effort: "medium" }, undefined)).toEqual({
      backend: "claude",
      model: "fable",
      effort: "medium",
    });
    expect(resolveImplRoute(undefined, { backend: "claude", model: "opus" })).toEqual({
      backend: "claude",
      model: "opus",
      effort: "",
    });
  });
});

describe("item-view Open in Code Build: linked session over new conversation", () => {
  const fleetSess = (over: Partial<{ uuid: string; source: string; projectPath?: string; mtime: number; title?: string; agent?: string }>) => ({
    uuid: "u-default",
    source: "claude",
    projectPath: "/Users/me/projects/repo",
    mtime: 1000,
    title: "t",
    ...over,
  });

  it("resumes the item's linked session when it resolves in the fleet list", () => {
    const t = resolveOpenCbTarget(["u-1"], [fleetSess({ uuid: "u-1", title: "impl session" })]);
    expect(t).toEqual({
      mode: "resume",
      uuid: "u-1",
      source: "claude",
      cwd: "/Users/me/projects/repo",
      title: "impl session",
    });
  });

  it("picks the most recently active linked session when several are linked", () => {
    const t = resolveOpenCbTarget(
      ["u-old", "u-new"],
      [fleetSess({ uuid: "u-old", mtime: 100 }), fleetSess({ uuid: "u-new", mtime: 200 })],
    );
    expect(t).toMatchObject({ mode: "resume", uuid: "u-new" });
  });

  it("falls back to a new conversation when nothing is linked", () => {
    expect(resolveOpenCbTarget([], [fleetSess({})])).toEqual({ mode: "new" });
    expect(resolveOpenCbTarget(undefined, [fleetSess({})])).toEqual({ mode: "new" });
  });

  it("missing — linked uuid not in the fleet, or no cwd — is not a silent new chat", () => {
    expect(resolveOpenCbTarget(["u-gone"], [fleetSess({ uuid: "u-other" })])).toEqual({ mode: "missing" });
    expect(resolveOpenCbTarget(["u-1"], [fleetSess({ uuid: "u-1", projectPath: undefined })])).toEqual({
      mode: "missing",
      uuid: "u-1",
    });
  });

  it("resumes git-store-only rows (maps source git → grok) instead of opening new", () => {
    const t = resolveOpenCbTarget(["u-1"], [fleetSess({ uuid: "u-1", source: "git", agent: "grok-build" })]);
    expect(t).toMatchObject({ mode: "resume", uuid: "u-1", source: "grok", cwd: "/Users/me/projects/repo" });
  });

  it("a native duplicate of the same uuid still wins over a git row without cwd", () => {
    const t = resolveOpenCbTarget(
      ["u-1"],
      [fleetSess({ uuid: "u-1", source: "git", projectPath: undefined, mtime: 900 }), fleetSess({ uuid: "u-1", mtime: 100 })],
    );
    expect(t).toMatchObject({ mode: "resume", uuid: "u-1", source: "claude" });
  });
  it("decodes claude's dash-encoded project dir to the real cwd (transcript lookup needs it)", () => {
    // claude rows store the ~/.claude/projects store dir, not the cwd — passing it
    // raw made CB re-encode it and miss the transcript ("Starting fresh").
    const t = resolveOpenCbTarget(
      ["u-1"],
      [fleetSess({ uuid: "u-1", projectPath: "/Users/me/.claude/projects/-Users-me-projects-repo" })],
    );
    expect(t).toMatchObject({ mode: "resume", cwd: "/Users/me/projects/repo" });
    // grok / already-decoded rows pass through unchanged
    const g = resolveOpenCbTarget(["u-2"], [fleetSess({ uuid: "u-2", source: "grok", projectPath: "/Users/me/docs" })]);
    expect(g).toMatchObject({ mode: "resume", cwd: "/Users/me/docs" });
  });
});

describe("Continue in Code Build: local JSONL / git-store / missing", () => {
  it("mapCbBackend never returns git (CB would open an empty panel)", () => {
    expect(mapCbBackend("git", "grok-build")).toBe("grok");
    expect(mapCbBackend("git", "claude")).toBe("claude");
    expect(mapCbBackend("claude", undefined)).toBe("claude");
    expect(mapCbBackend("grok", undefined)).toBe("grok");
    expect(mapCbBackend("git", undefined)).toBe("grok");
    expect(mapCbBackend("codex", undefined)).toBeNull();
  });

  it("isNativeTranscriptPath rejects git-store session.json", () => {
    expect(isNativeTranscriptPath("/Users/me/.sessions/hosts/air/2026-09/abc/session.json")).toBe(false);
    expect(isNativeTranscriptPath("/Users/me/.claude/projects/-Users-me-docs/abc.jsonl")).toBe(true);
    expect(isNativeTranscriptPath("/Users/me/.grok/sessions/%2Fdocs/abc/chat_history.jsonl")).toBe(true);
    expect(isNativeTranscriptPath(undefined)).toBe(false);
  });

  it("plan: local JSONL present → native resume", () => {
    const p = planContinueInCodeBuild({
      uuid: "u-1",
      source: "claude",
      projectPath: "/Users/me/docs",
      nativeJsonl: true,
      storeTurns: false,
    });
    expect(p).toEqual({ action: "native", source: "claude", cwd: "/Users/me/docs", uuid: "u-1", title: undefined });
  });

  it("plan: git-store-only transcript → hydrate (not missing, not silent new)", () => {
    const p = planContinueInCodeBuild(
      {
        uuid: "u-2",
        source: "git",
        agent: "grok-build",
        projectPath: "/Users/me/projects/csv",
        nativeJsonl: false,
        storeTurns: true,
        storeHost: "air-15",
        title: "done item",
      },
      "/fallback",
    );
    expect(p).toEqual({
      action: "git-store",
      source: "grok",
      cwd: "/Users/me/projects/csv",
      uuid: "u-2",
      title: "done item",
      host: "air-15",
    });
  });

  it("plan: missing transcript → missing (toast path)", () => {
    expect(
      planContinueInCodeBuild({
        uuid: "u-3",
        source: "git",
        nativeJsonl: false,
        storeTurns: false,
      }),
    ).toEqual({ action: "missing" });
    expect(
      planContinueInCodeBuild({
        uuid: "u-3",
        nativeJsonl: false,
        storeTurns: true,
      }),
    ).toEqual({ action: "missing" });
  });

  it("plan: git-store without cwd uses fallback cwd", () => {
    const p = planContinueInCodeBuild(
      { uuid: "u-4", source: "git", nativeJsonl: false, storeTurns: true, storeHost: "air" },
      "/Users/me/docs",
    );
    expect(p).toMatchObject({ action: "git-store", cwd: "/Users/me/docs", source: "grok" });
  });
});
